spring.application.name=first-api

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=senai
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# H2 é um SGBD escrito em Java, leve, rápido é fácil de configurar. Suporta
# modos de operação de banco de dados embutido, servidor e memória. Já vem instalado e pré-configurado no Springboot.
# É bom para testes e estudos, mas não para produção.